name: CI
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar tu código (Versión v4 actualizada)
      - uses: actions/checkout@v4

      # 2. Preparar Python 3.10 (Estable para Kivy)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Instalar Dependencias de Linux (Esenciales para compilar Android)
      # Esta lista incluye todo lo necesario para evitar errores de "missing library"
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip build-essential git python3 \
            python3-dev ffmpeg libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
            libswscale-dev libavformat-dev libavcodec-dev \
            zlib1g-dev libgstreamer1.0-dev gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good openjdk-17-jdk \
            libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev \
            libssl-dev openssl libgdbm-dev libgdbm-compat-dev \
            liblzma-dev libreadline-dev libncursesw5-dev \
            libffi-dev uuid-dev libopenjp2-7 autoconf libtool

      # 4. Instalar Buildozer y Cython
      - name: Install Buildozer
        run: |
          # Usamos una versión de Cython compatible
          pip install buildozer "cython<3.0.0"

      # 5. Ejecutar la Compilación
      # "yes |" sirve para aceptar automáticamente las licencias de Android SDK
      - name: Build with Buildozer
        run: |
          yes | buildozer android debug

      # 6. Subir el APK resultante para descargar (Versión v4 actualizada)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
          if-no-files-found: error
